[package]
name = "swell-ui"
version = "0.1.0"
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>"]
edition = "2021"

[dependencies]
reaper-low = { git = "https://github.com/helgoboss/reaper-rs.git", branch = "master" }
rxrust = { git = "https://github.com/rxRust/rxRust", rev = "349e50b3197e05926e2378ef8fc45cb67ad43b83" }
rx-util = { path = "../rx-util" }
scopeguard = "1.1.0"
raw-window-handle = "0.4.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser", "uxtheme"] }
palette = "0.5"

[build-dependencies]
bindgen = "0.52.0"