[package]
name = "swell-ui"
version = "0.1.0"
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>"]
edition = "2021"

[dependencies]
reaper-medium = { git = "https://github.com/helgoboss/reaper-rs.git", branch = "master" }
reaper-low = { git = "https://github.com/helgoboss/reaper-rs.git", branch = "master" }
rxrust = { git = "https://github.com/rxRust/rxRust", rev = "349e50b3197e05926e2378ef8fc45cb67ad43b83" }
rx-util = { path = "../rx-util" }
scopeguard = "1.1.0"
raw-window-handle = "0.4.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser", "uxtheme"] }
palette = "0.5"
libloading = "0.7"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.3.0-beta.3"


# Disabled until we get egui to work nicely (search for "wonky"). It's also important to use cross v0.3.0 then
# (once it's released) because cross v2.5 uses Ubuntu < v20, which has an old glib that's not compatible with the
# glib crate (gdk-sys dependency).
# [target.'cfg(target_os = "linux")'.dependencies]
# gdk-sys = "0.17.0"
# gdkx11-sys = "0.17.0"

[build-dependencies]
bindgen = "0.60.1"