= Target "ReaLearn: Enable/disable instances"

This target allows you to flexibly enable or disable other ReaLearn instances based on instance or unit tags.

== Tag kind menu

Instance tags::
A ReaLearn instance matches when at least one of its units is tagged with any of the xref:further-concepts/instance.adoc#instance-tag[instance tags] entered into the **tags** field.

Unit tags::
A ReaLearn instance matches when at least one of its units is tagged with any of the xref:further-concepts/unit.adoc#unit-tag[unit tags] entered into the **tags** field.
+
WARNING: Controlling instances via unit tags can be counter-intuitive, please use instance tags instead! This option is retained for backward compatibility only.


== Exclusivity menu

Non-exclusive:: If the incoming control value is greater than 0%, all matching ReaLearn instances will be enabled (on top of the already enabled instances).
If the value is 0%, all matching ReaLearn instances will be disabled.

Exclusive:: If the incoming control value is greater than 0%, all matching ReaLearn instances will be enabled and all non-matching ones will be disabled.
If the value is 0%, it's exactly the opposite (react to button xref:user-interface/mapping-panel/glue-section.adoc#press-only[press only] if you don't want this to happen).

Exclusive (on only):: Variation of _Exclusive_ that applies exclusivity only if the incoming control value is greater than 0%.

== Tags field

Here you enter the instance or unit tags, separated by commas.

.Comma-separated tags
====
keys, guit, voc
====

== Remarks

* This affects other ReaLearn instances only. It doesn't match against this one.
* ReaLearn instances without tags won't be affected at all.
* Only affects instances in the same project.
If _this_ ReaLearn instance is on the monitoring FX chain, it only affects other instances in the monitoring FX chain.

TIP: This target is great for switching between completely different controller setups!