on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  # For quickly detecting important differences in runner configurations
  schedule:
    - cron: '0 5 * * MON'

name: Linux aarch64

jobs:
  check:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      # Checkout with Playtime Clip Engine
      - uses: actions/checkout@v2
      - name: Update submodules
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.PRIVATE_PLAYTIME_CLIP_ENGINE_DEPLOY_KEY }}"
          git submodule update --init
      # Remainder
      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install nasm php libxdo-dev libx11-dev libxcursor-dev libxcb-dri2-0-dev libxcb-icccm4-dev libx11-xcb-dev mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev libspeechd-dev libgtk-3-dev
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.68.2
          target: aarch64-unknown-linux-gnu
          override: true
      - name: cargo test (for generating dialogs with php)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --all-features --target aarch64-unknown-linux-gnu