on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  # For quickly detecting important differences in runner configurations
  schedule:
    - cron: '0 5 * * MON'

name: macOS x86_64

jobs:
  check:
    name: Check
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: brew install php
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.68.2
          override: true
      - run: rustup component add rustfmt
      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test
    runs-on: macos-latest
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.7
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: brew install php
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.68.2
          override: true
      - run: rustup component add rustfmt
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v2
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --nocapture
