on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  # For quickly detecting important differences in runner configurations
  schedule:
    - cron: '0 5 * * MON'

name: macOS x86_64

jobs:
  check:
    name: Check
    runs-on: macos-latest
    steps:
      # Checkout with Playtime Clip Engine
      - uses: actions/checkout@v2
      - name: Update submodules
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.PRIVATE_PLAYTIME_CLIP_ENGINE_DEPLOY_KEY }}"
          git submodule update --init
      # Remainder
      - run: brew install php
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.68.2
          override: true
      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features

  test:
    name: Test
    runs-on: macos-latest
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.7
    steps:
      # Checkout with Playtime Clip Engine
      - uses: actions/checkout@v2
      - name: Update submodules
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.PRIVATE_PLAYTIME_CLIP_ENGINE_DEPLOY_KEY }}"
          git submodule update --init
      # Remainder
      - run: brew install php
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.68.2
          override: true
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v2
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features -- --nocapture
