on:
  create:
    ref_type: tag
    ref: 'v*'

name: Create release

jobs:

  build-release-artifacts:
    name: Build artifact
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - artifact: windows-x86_64
            os: windows-latest
            toolchain-suffix: x86_64-pc-windows-msvc
            lib-file-name: realearn.dll
            target: x86_64-pc-windows-msvc
            use-cross: false
            profile: release
          - artifact: windows-i686
            os: windows-latest
            toolchain-suffix: i686-pc-windows-msvc
            lib-file-name: realearn.dll
            target: i686-pc-windows-msvc
            use-cross: false
            profile: release-llvm-out-of-memory-fix
          - artifact: macos-x86_64
            os: macos-latest
            toolchain-suffix: x86_64-apple-darwin
            lib-file-name: librealearn.dylib
            target: x86_64-apple-darwin
            use-cross: false
            profile: release
          - artifact: macos-aarch64
            os: macos-latest
            toolchain-suffix: x86_64-apple-darwin
            lib-file-name: librealearn.dylib
            target: aarch64-apple-darwin
            use-cross: false
            profile: release
          - artifact: linux-x86_64
            os: ubuntu-latest
            toolchain-suffix: x86_64-unknown-linux-gnu
            lib-file-name: librealearn.so
            target: x86_64-unknown-linux-gnu
            use-cross: false
            strip-cmd: strip
            profile: release
          - artifact: linux-aarch64
            os: ubuntu-latest
            toolchain-suffix: x86_64-unknown-linux-gnu
            lib-file-name: librealearn.so
            target: aarch64-unknown-linux-gnu
            use-cross: true
            strip-cmd: aarch64-linux-gnu-strip
            profile: release
          - artifact: linux-armv7
            os: ubuntu-latest
            toolchain-suffix: x86_64-unknown-linux-gnu
            lib-file-name: librealearn.so
            target: armv7-unknown-linux-gnueabihf
            use-cross: true
            strip-cmd: arm-linux-gnueabihf-strip
            profile: release
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.7 # This is relevant for macOS builds only (and only if not overridden).
    steps:
      # Prepare (all)
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.63.0-${{ matrix.toolchain-suffix }}
          target: ${{ matrix.target }}
          override: true
      - run: rustup component add rustfmt
      # Install OS dependencies (Linux/macOS only)
      - name: Install native Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install nasm php binutils-arm-linux-gnueabihf binutils-aarch64-linux-gnu libxdo-dev libx11-dev libxcursor-dev libxcb-dri2-0-dev libxcb-icccm4-dev libx11-xcb-dev mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev libspeechd-dev
      - run: brew install php
        if: matrix.os == 'macos-latest'
      # Override SDK root and deployment target (macOS aarch64 only)
      - name: Set SDKROOT
        if: matrix.target == 'aarch64-apple-darwin'
        run: echo "SDKROOT=$(xcrun -sdk macosx11.1 --show-sdk-path)" >> $GITHUB_ENV
      - name: Set MACOSX_DEPLOYMENT_TARGET
        if: matrix.target == 'aarch64-apple-darwin'
        run: echo "MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx11.1 --show-sdk-platform-version)" >> $GITHUB_ENV
      # Generate dialogs outside of Docker containers in cross builds because PHP is not available in container
      - name: cargo test (for generating dialogs with php)
        if: matrix.use-cross == true
        uses: actions-rs/cargo@v1
        with:
          command: test
      # Build (all)
      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --profile ${{ matrix.profile }} --target ${{ matrix.target }}
          use-cross: ${{ matrix.use-cross }}
      # Strip debug symbols (Linux and macOS)
      # TODO-medium We could replace this with Cargo's recent built-in strip function
      - name: Strip debug symbols from Linux binary
        if: matrix.os == 'ubuntu-latest'
        run: |
          cp target/${{ matrix.target }}/${{ matrix.profile }}/${{ matrix.lib-file-name }} target/${{ matrix.target }}/${{ matrix.profile }}/librealearn-debug.so
          ${{ matrix.strip-cmd }} target/${{ matrix.target }}/${{ matrix.profile }}/${{ matrix.lib-file-name }}
      - name: Strip debug symbols from macOS binary
        if: matrix.os == 'macos-latest'
        run: |
          strip -u -r target/${{ matrix.target }}/${{ matrix.profile }}/${{ matrix.lib-file-name }}
      # Upload plug-in (all)
      - name: Upload plug-in to artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: target/${{ matrix.target }}/${{ matrix.profile }}/${{ matrix.lib-file-name }}
      # Upload debug symbols (all)
      - name: Upload Windows debug symbols to artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: target/${{ matrix.target }}/${{ matrix.profile }}/realearn.pdb
      - name: Upload macOS debug symbols to artifact
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: target/${{ matrix.target }}/${{ matrix.profile }}/deps/librealearn.dylib.dSYM/
      - name: Upload Linux debug symbols to artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: target/${{ matrix.target }}/${{ matrix.profile }}/librealearn-debug.so

  create-release:
    name: Publish release
    needs: build-release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.get_tag_name.outputs.TAG_NAME }}
          release_name: ${{ steps.get_tag_name.outputs.TAG_NAME }}
          draft: true
          prerelease: ${{ contains(github.ref, 'pre') }}
      - name: Download artifacts from build job
        uses: actions/download-artifact@v2
      - name: Upload windows-x86_64 release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows-x86_64/realearn.dll
          asset_name: realearn-windows-x86_64.dll
          asset_content_type: application/octet-stream
      - name: Upload windows-i686 release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows-i686/realearn.dll
          asset_name: realearn-windows-i686.dll
          asset_content_type: application/octet-stream
      - name: Upload macos-x86_64 release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./macos-x86_64/librealearn.dylib
          asset_name: realearn-macos-x86_64.vst.dylib
          asset_content_type: application/octet-stream
      - name: Upload macos-aarch64 release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./macos-aarch64/librealearn.dylib
          asset_name: realearn-macos-aarch64.vst.dylib
          asset_content_type: application/octet-stream
      - name: Upload linux-x86_64 release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./linux-x86_64/librealearn.so
          asset_name: realearn-linux-x86_64.so
          asset_content_type: application/octet-stream
      - name: Upload linux-aarch64 release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./linux-aarch64/librealearn.so
          asset_name: realearn-linux-aarch64.so
          asset_content_type: application/octet-stream
      - name: Upload linux-armv7 release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./linux-armv7/librealearn.so
          asset_name: realearn-linux-armv7.so
          asset_content_type: application/octet-stream